//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IJobInspection")]
public interface IJobInspection
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobInspection/Echo", ReplyAction="http://tempuri.org/IJobInspection/EchoResponse")]
    string Echo(string returnThis);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IJobInspectionChannel : IJobInspection, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class JobInspectionClient : System.ServiceModel.ClientBase<IJobInspection>, IJobInspection
{
    
    public JobInspectionClient()
    {
    }
    
    public JobInspectionClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public JobInspectionClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public JobInspectionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public JobInspectionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string Echo(string returnThis)
    {
        return base.Channel.Echo(returnThis);
    }
}
