//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFIDataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActionReport
    {
        public int ID { get; set; }
        public int OrderID { get; set; }
        public Nullable<System.DateTime> ReportDate { get; set; }
        public string Nature { get; set; }
        public string ActionRequired { get; set; }
        public string Cause { get; set; }
        public Nullable<bool> Closed { get; set; }
        public Nullable<int> StoreError { get; set; }
        public Nullable<int> MillError { get; set; }
        public Nullable<int> InstallerError { get; set; }
        public Nullable<int> MeasureError { get; set; }
        public string StoreErrorText { get; set; }
        public string MillErrorText { get; set; }
        public string InstallerErrorText { get; set; }
        public string MeasureErrorText { get; set; }
        public Nullable<int> EnteredBy { get; set; }
        public Nullable<System.DateTime> LastEditedDate { get; set; }
        public Nullable<int> LastEditedBy { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
