//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFIDataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CapacityPool
    {
        public int ID { get; set; }
        public string HDPoolID { get; set; }
        public int PoolTypeID { get; set; }
        public string PoolName { get; set; }
        public string ZoneName { get; set; }
        public string ZoneNumber { get; set; }
        public int VendorID { get; set; }
    }
}
