//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFIDataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckCBDetail
    {
        public int CheckCBDetailID { get; set; }
        public int CheckID { get; set; }
        public int ChargeBackID { get; set; }
        public decimal Amount { get; set; }
    
        public virtual ChargeBack ChargeBack { get; set; }
        public virtual Check Check { get; set; }
    }
}
