//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFIDataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Check
    {
        public Check()
        {
            this.CheckCBDetails = new HashSet<CheckCBDetail>();
            this.CheckDetails = new HashSet<CheckDetail>();
        }
    
        public int CheckID { get; set; }
        public string CheckNumber { get; set; }
        public Nullable<System.DateTime> CheckDate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public int VendorID { get; set; }
    
        public virtual ICollection<CheckCBDetail> CheckCBDetails { get; set; }
        public virtual ICollection<CheckDetail> CheckDetails { get; set; }
    }
}
