//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFIDataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepartmentsContactTitle
    {
        public int DepartmentsID { get; set; }
        public int ContactTitlesID { get; set; }
        public Nullable<bool> Required { get; set; }
    
        public virtual ContactTitle ContactTitle { get; set; }
        public virtual Department Department { get; set; }
    }
}
