//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFIDataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Discrepancy
    {
        public int ID { get; set; }
        public Nullable<int> DiscrepancyTypeID { get; set; }
        public Nullable<int> DiscrepancySubTypeID { get; set; }
        public string CurrentData { get; set; }
        public string NewData { get; set; }
        public string XMLFilePath { get; set; }
        public System.DateTime DateFound { get; set; }
        public int OrderID { get; set; }
        public Nullable<int> DetailID { get; set; }
        public bool Reviewed { get; set; }
        public int ReviewedBy { get; set; }
        public Nullable<System.DateTime> DateReviewed { get; set; }
    }
}
