//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFIDataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiscrepanciesPrice
    {
        public int ID { get; set; }
        public int DiscrepancyTypeID { get; set; }
        public int ItemID { get; set; }
        public int MarketID { get; set; }
        public Nullable<decimal> CurrentPrice { get; set; }
        public Nullable<decimal> NewPrice { get; set; }
        public string XMLFilePath { get; set; }
        public System.DateTime DateFound { get; set; }
    }
}
