//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFIDataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Division
    {
        public Division()
        {
            this.MaterialTypes = new HashSet<MaterialType>();
        }
    
        public int DivisionID { get; set; }
        public string Division1 { get; set; }
        public Nullable<int> VendorID { get; set; }
        public int DivisionGroupID { get; set; }
        public bool PrintStatusReport { get; set; }
        public bool MarkBilledWhenPaid { get; set; }
    
        public virtual ICollection<MaterialType> MaterialTypes { get; set; }
    }
}
