//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFIDataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Issue
    {
        public int ID { get; set; }
        public int AddedByUser { get; set; }
        public System.DateTime DateAdded { get; set; }
        public string Description { get; set; }
        public int StatusID { get; set; }
        public Nullable<System.DateTime> StatusDate { get; set; }
        public string Comment { get; set; }
    }
}
