//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFIDataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Market
    {
        public Market()
        {
            this.Stores = new HashSet<Store>();
        }
    
        public int MarketId { get; set; }
        public string MarketName { get; set; }
        public string BranchPrinterName { get; set; }
        public string BranchPrinterPort { get; set; }
        public string BranchPrinterDriver { get; set; }
    
        public virtual ICollection<Store> Stores { get; set; }
    }
}
