//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFIDataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material_Catagory
    {
        public int CatId { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsPadding { get; set; }
        public Nullable<int> YardsPerRoll { get; set; }
        public Nullable<int> UnitOfMeasureID { get; set; }
        public Nullable<int> SubCatId { get; set; }
    }
}
