//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFIDataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialType
    {
        public MaterialType()
        {
            this.Options = new HashSet<Option>();
        }
    
        public int MaterialTypeID { get; set; }
        public Nullable<int> StoreTypeID { get; set; }
        public Nullable<decimal> MinimumPrice { get; set; }
        public Nullable<decimal> MinimumCost { get; set; }
        public Nullable<decimal> MinimumRetail { get; set; }
        public Nullable<double> CustomMultiplier { get; set; }
        public Nullable<double> TripChargeMultiplier { get; set; }
        public Nullable<double> CostMultiplier { get; set; }
        public Nullable<bool> Valid { get; set; }
        public Nullable<bool> OnlyBasicToMinimum { get; set; }
        public string ShortName { get; set; }
        public Nullable<int> DivisionID { get; set; }
        public Nullable<bool> Active { get; set; }
        public bool Furnish { get; set; }
        public string SKU { get; set; }
        public string SKUDesc { get; set; }
        public string HDType { get; set; }
        public string MaterialTypeName { get; set; }
        public bool InsuranceReplacement { get; set; }
        public bool AllowMaterialStatusUpdate { get; set; }
    
        public virtual Division Division { get; set; }
        public virtual StoreType StoreType { get; set; }
        public virtual ICollection<Option> Options { get; set; }
    }
}
