//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFIDataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeasureCompLineItemData
    {
        public int ID { get; set; }
        public int CalcID { get; set; }
        public int LineItemNumber { get; set; }
        public string MaterialType { get; set; }
        public string MaterialDescription { get; set; }
        public Nullable<int> MaterialWidth { get; set; }
        public string PatternMatch { get; set; }
        public string MaterialAmount { get; set; }
    
        public virtual MeasureCompCalcData MeasureCompCalcData { get; set; }
    }
}
