//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFIDataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeasureCompOrderData
    {
        public int ID { get; set; }
        public int OrderID { get; set; }
        public Nullable<bool> Heat { get; set; }
        public Nullable<bool> Pets { get; set; }
        public Nullable<bool> Electricity { get; set; }
        public Nullable<bool> FurnitureMoving { get; set; }
        public Nullable<bool> NewPaint { get; set; }
        public Nullable<bool> Removal { get; set; }
        public Nullable<bool> PavedDriveway { get; set; }
        public Nullable<bool> Garage { get; set; }
        public Nullable<bool> Elevator { get; set; }
        public string Disposal { get; set; }
        public string Access { get; set; }
        public string SiteType { get; set; }
        public string MetalColor { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
