//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFIDataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NoteType
    {
        public int ID { get; set; }
        public string NoteTypeDescription { get; set; }
        public bool ShowInList { get; set; }
        public bool ShowEmployees { get; set; }
        public bool ShowSpokeWith { get; set; }
        public bool RequireSpokeWith { get; set; }
        public bool EnableSchedulingInfo { get; set; }
        public bool CanSendToExpeditor { get; set; }
        public bool ShowStoreManagement { get; set; }
        public bool PermissionRequiredToSelect { get; set; }
        public Nullable<byte> DisplayOrder { get; set; }
    }
}
