//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFIDataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OldCarpet
    {
        public int Id { get; set; }
        public string PoNumber_Original { get; set; }
        public string SoNumber { get; set; }
        public string PoNumber_Replacement { get; set; }
        public string Name { get; set; }
        public string Store { get; set; }
        public Nullable<int> MaterialStatusId { get; set; }
        public string Comments { get; set; }
    }
}
