//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFIDataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Option
    {
        public Option()
        {
            this.Order_Options_Details = new HashSet<Order_Options_Detail>();
        }
    
        public int OptionID { get; set; }
        public string OptionDescription { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> UnitCost { get; set; }
        public Nullable<int> UnitOfMeasureID { get; set; }
        public Nullable<int> MaterialTypeID { get; set; }
        public Nullable<decimal> RetailPrice { get; set; }
        public Nullable<bool> IsPadding { get; set; }
        public Nullable<int> YardsPerRoll { get; set; }
        public Nullable<bool> ApplyToMinimum { get; set; }
        public Nullable<bool> PrintOnInvoice { get; set; }
        public Nullable<bool> PrintOnWorkOrder { get; set; }
        public Nullable<int> MaterialCatagoryID { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> ApplyToMinimumWO { get; set; }
        public bool Furnish { get; set; }
        public Nullable<int> MaterialCost { get; set; }
    
        public virtual MaterialType MaterialType { get; set; }
        public virtual UnitOfMeasure UnitOfMeasure { get; set; }
        public virtual ICollection<Order_Options_Detail> Order_Options_Details { get; set; }
    }
}
