//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFIDataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderCustomDetailsDeleted
    {
        public int ID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<int> SubContractorID { get; set; }
        public Nullable<decimal> RetailPrice { get; set; }
        public Nullable<double> Multiplier { get; set; }
        public Nullable<decimal> UnitCost { get; set; }
        public Nullable<double> Quanity { get; set; }
        public string Description { get; set; }
        public Nullable<double> CostMultiplier { get; set; }
        public Nullable<int> UnitOfMeasureID { get; set; }
        public Nullable<bool> NotOnInvoice { get; set; }
        public Nullable<bool> NotOnWorkOrder { get; set; }
        public Nullable<bool> SubContractorPaid { get; set; }
        public Nullable<double> SubContractorPay { get; set; }
        public Nullable<int> EntryMethodID { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<int> OriginalID { get; set; }
    }
}
