//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFIDataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDiagram
    {
        public int ID { get; set; }
        public int OrderID { get; set; }
        public string DiagramNumber { get; set; }
        public Nullable<System.DateTime> DiagramDateTime { get; set; }
        public string DiagramFileName { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
