//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFIDataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderExtra
    {
        public int ID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> UnitCost { get; set; }
        public Nullable<double> Quantity { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
