//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFIDataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderSOMerchandiseDetail
    {
        public int ID { get; set; }
        public int OrderID { get; set; }
        public string SONumber { get; set; }
        public string SKUNumber { get; set; }
        public Nullable<int> BasicLaborID { get; set; }
        public string ShortDescription { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<int> UOMId { get; set; }
        public Nullable<System.DateTime> ExpectedArrivalDate { get; set; }
        public Nullable<int> SOLineNumber { get; set; }
        public Nullable<int> MaterialStatusID { get; set; }
        public int EntryMethodID { get; set; }
        public bool Deleted { get; set; }
        public Nullable<int> TransferredTo { get; set; }
        public Nullable<int> TransferredFrom { get; set; }
        public Nullable<int> SOMerLineNumber { get; set; }
        public Nullable<int> OriginalID { get; set; }
        public Nullable<decimal> PreSplitQty { get; set; }
        public Nullable<int> XMLStatusID { get; set; }
        public bool Reviewed { get; set; }
        public Nullable<int> ReviewedBy { get; set; }
        public Nullable<System.DateTime> ReviewedDate { get; set; }
        public Nullable<int> WillCallLineNumber { get; set; }
        public Nullable<int> OriginalOrderID { get; set; }
    
        public virtual Material_Status Material_Status { get; set; }
        public virtual Order Order { get; set; }
    }
}
