//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFIDataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPNActionQueue
    {
        public int ID { get; set; }
        public int ActionID { get; set; }
        public string DataField1 { get; set; }
        public string DataField2 { get; set; }
        public string DataField3 { get; set; }
        public string DataField4 { get; set; }
        public Nullable<System.DateTime> SendAfter { get; set; }
        public bool Processed { get; set; }
    }
}
