//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFIDataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpokeWith
    {
        public int SpokeWith1 { get; set; }
        public string SW_Text { get; set; }
        public bool ShowAlways { get; set; }
        public byte DisplayOrder { get; set; }
        public bool EnableSchedulingInfo { get; set; }
    }
}
