//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFIDataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusDetail
    {
        public string StoreNumber { get; set; }
        public string PONumber { get; set; }
        public Nullable<int> POGroup { get; set; }
        public Nullable<int> DivisionID { get; set; }
        public Nullable<int> DivisionGroupID { get; set; }
        public Nullable<bool> InsuranceReplacement { get; set; }
        public Nullable<int> LineIndex { get; set; }
        public string LineString { get; set; }
    }
}
