//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFIDataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store
    {
        public Store()
        {
            this.DepartmentsStoresAssignments = new HashSet<DepartmentsStoresAssignment>();
            this.Orders = new HashSet<Order>();
            this.StoreContacts = new HashSet<StoreContact>();
        }
    
        public int StoreID { get; set; }
        public Nullable<int> StoreTypeID { get; set; }
        public string StoreNumber { get; set; }
        public string BillingAddress { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string StorePhoneNumber { get; set; }
        public string DirectPhoneNumber { get; set; }
        public string Extension { get; set; }
        public string FaxNumber { get; set; }
        public string Notes { get; set; }
        public Nullable<int> MarketId { get; set; }
        public bool Active { get; set; }
        public string StoreNickName { get; set; }
        public int XMLSourceID { get; set; }
        public bool IncludeInStatusReportAll { get; set; }
    
        public virtual ICollection<DepartmentsStoresAssignment> DepartmentsStoresAssignments { get; set; }
        public virtual Market Market { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<StoreContact> StoreContacts { get; set; }
        public virtual StoreType StoreType { get; set; }
    }
}
