//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFIDataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitOfMeasure
    {
        public UnitOfMeasure()
        {
            this.Options = new HashSet<Option>();
        }
    
        public int UnitOfMeasureID { get; set; }
        public string Description { get; set; }
        public int Divisor { get; set; }
        public Nullable<int> NumberOfDecimals { get; set; }
        public string LongDescription { get; set; }
        public string LongDescriptionSOSI { get; set; }
    
        public virtual ICollection<Option> Options { get; set; }
    }
}
