//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFIDataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMarketDivisionAssignment
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public int MarketID { get; set; }
        public int DivisionID { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
