//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFIDataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorNumber
    {
        public int VendorID { get; set; }
        public string VendorNumber1 { get; set; }
        public string Description { get; set; }
        public string HDDescription { get; set; }
        public Nullable<bool> PaySubWhenPaid { get; set; }
    }
}
