//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFIDataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Version
    {
        public int VersionID { get; set; }
        public Nullable<int> VersionNo { get; set; }
        public Nullable<int> MinimumVersionMajor { get; set; }
        public Nullable<int> MinimumVersionMinor { get; set; }
    }
}
